In [1]:
import seaborn as sns
import pandas as pd  #Using these imports that are the necessary libraries to start with the EDA

In [2]:
transport_df = pd.read_csv('luas.csv') # I am using pandas to read our data and transforming it into a dataframe

In [3]:
transport_df

,STATISTIC,Statistic Label,TLIST(A1),Year,C01885V02316,Month,UNIT,VALUE
0,TOA11C01,Red line,2018,2018,01,January,Number,1664495
1,TOA11C01,Red line,2018,2018,02,February,Number,1657562
2,TOA11C01,Red line,2018,2018,03,March,Number,1661098
3,TOA11C01,Red line,2018,2018,04,April,Number,1794424
4,TOA11C01,Red line,2018,2018,05,May,Number,1934553
...,...,...,...,...,...,...,...,...
190,TOA11C03,All Luas lines,2022,2022,09,September,Number,3811093
191,TOA11C03,All Luas lines,2022,2022,10,October,Number,4219124
192,TOA11C03,All Luas lines,2022,2022,11,November,Number,4375705
193,TOA11C03,All Luas lines,2022,2022,12,December,Number,4030698
194,TOA11C03,All Luas lines,2022,2022,-,All months,Number,38667875

In [4]:
transport_df = transport_df.rename(columns={"VALUE": 'Passengers Luas' })

In [5]:
transport_df.drop(transport_df[transport_df['Statistic Label'] == 'Red line'].index, axis=0, inplace=True)

In [6]:
transport_df.drop(transport_df[transport_df['Statistic Label'] == 'Green line'].index, axis=0, inplace=True)

In [7]:
transport_df.drop(transport_df[transport_df['Month'] == 'All months'].index, axis=0, inplace=True)

In [8]:
transport_df.drop(columns=['STATISTIC'], inplace=True)

In [9]:
transport_df.drop(columns=['TLIST(A1)'], inplace=True)

In [10]:
transport_df.drop(columns=['UNIT'], inplace=True)

In [11]:
transport_df.drop(columns=['C01885V02316'], inplace=True)

In [12]:
transport_df.drop(columns=['Statistic Label'], inplace=True)

In [13]:
tren_df = pd.read_excel('ETUP_GDL_T1.xlsx', sheet_name='Tabulado', skiprows=[0, 1, 2,64,65,66,67,68,69,70,71,72,73,74,75])

In [14]:
tren_df = tren_df.rename(columns={"Año": 'Year' })

In [15]:
tren_df = tren_df.rename(columns={"Mes": 'Month' })

In [84]:
#tren_df = tren_df.rename(columns={"Pasajeros transportados (Miles de  pasajeros)": 'Passengers Tren' })

In [86]:
#tren_df = tren_df.rename(columns={"Ingresos por pasaje (Miles de pesos)": 'Revenue Tren' })

In [16]:
print(tren_df.columns)

Index(['Ciudad', 'Year', 'Month',
       'Pasajeros transportados (Miles de  pasajeros)',
       'Ingresos por pasaje (Miles de pesos)'],
      dtype='object')

In [18]:
tren_df['Passengers Tren'] = tren_df['Pasajeros transportados (Miles de  pasajeros)'] * 1000

In [59]:
transport_df.shape

(60, 3)

In [23]:
tren_df

,Ciudad,Year,Month,Pasajeros transportados (Miles de pasajeros),Ingresos por pasaje (Miles de pesos),Passengers Tren,Revenue Tren
0,Guadalajara,2018,Enero,8287.8,41846.1,8287800.0,2237759.36
1,Guadalajara,2018,Febrero,8033.9,39811.3,8033900.0,2128946.52
2,Guadalajara,2018,Marzo,8441.4,42917.6,8441400.0,2295058.82
3,Guadalajara,2018,Abril,8315.5,45080.9,8315500.0,2410743.32
4,Guadalajara,2018,Mayo,8899.0,48710.0,8899000.0,2604812.83
5,Guadalajara,2018,Junio,8269.9,44589.5,8269900.0,2384465.24
6,Guadalajara,2018,Julio,8517.5,46772.7,8517500.0,2501213.90
7,Guadalajara,2018,Agosto,9023.6,49363.6,9023600.0,2639764.71
8,Guadalajara,2018,Septiembre,8716.6,47289.6,8716600.0,2528855.61
9,Guadalajara,2018,Octubre,9590.6,50896.7,9590600.0,2721748.66
10,Guadalajara,2018,Noviembre,8979.2,48887.8,8979200.0,2614320.86
11,Guadalajara,2018,Diciembre,8573.6,48535.3,8573600.0,2595470.59
12,Guadalajara,2019,Enero,8942.9,48699.3,8942900.0,2604240.64
13,Guadalajara,2019,Febrero,8138.6,46408.7,8138600.0,2481748.66
14,Guadalajara,2019,Marzo,8813.1,48655.0,8813100.0,2601871.66
15,Guadalajara,2019,Abril,7859.2,47049.2,7859200.0,2516000.00
16,Guadalajara,2019,Mayo,8810.3,47794.8,8810300.0,2555871.66
17,Guadalajara,2019,Junio,8158.1,48612.2,8158100.0,2599582.89
18,Guadalajara,2019,Julio,8362.3,48976.0,8362300.0,2619037.43
19,Guadalajara,2019,Agosto,8254.4,48270.1,8254400.0,2581288.77
20,Guadalajara,2019,Septiembre,7876.2,43352.5,7876200.0,2318315.51
21,Guadalajara,2019,Octubre,8695.0,50071.6,8695000.0,2677625.67
22,Guadalajara,2019,Noviembre,8341.4,46974.5,8341400.0,2512005.35
23,Guadalajara,2019,Diciembre,8181.6,45921.2,8181600.0,2455679.14
24,Guadalajara,2020,Enero,7813.4,45270.4,7813400.0,2420877.01
25,Guadalajara,2020,Febrero,7913.6,49090.2,7913600.0,2625144.39
26,Guadalajara,2020,Marzo,6160.5,36162.3,6160500.0,1933812.83
27,Guadalajara,2020,Abril,3032.0,18192.2,3032000.0,972844.92
28,Guadalajara,2020,Mayo,3679.7,21710.3,3679700.0,1160978.61
29,Guadalajara,2020,Junio,4519.7,26187.6,4519700.0,1400406.42
30,Guadalajara,2020,Julio,5044.3,30031.3,5044300.0,1605951.87
31,Guadalajara,2020,Agosto,5278.7,31306.6,5278700.0,1674149.73
32,Guadalajara,2020,Septiembre,6141.6,31373.1,6141600.0,1677705.88
33,Guadalajara,2020,Octubre,8569.5,31421.1,8569500.0,1680272.73
34,Guadalajara,2020,Noviembre,7330.4,31451.6,7330400.0,1681903.74
35,Guadalajara,2020,Diciembre,8770.6,31463.5,8770600.0,1682540.11
36,Guadalajara,2021,Enero,7027.2,31455.7,7027200.0,1682122.99
37,Guadalajara,2021,Febrero,7046.4,31432.2,7046400.0,1680866.31
38,Guadalajara,2021,Marzo,8583.8,31896.3,8583800.0,1705684.49
39,Guadalajara,2021,Abril,8260.3,31594.7,8260300.0,1689556.15
40,Guadalajara,2021,Mayo,9140.1,31520.1,9140100.0,1685566.84
41,Guadalajara,2021,Junio,9522.4,31579.8,9522400.0,1688759.36
42,Guadalajara,2021,Julio,10028.3,31367.9,10028300.0,1677427.81
43,Guadalajara,2021,Agosto,9894.7,31279.8,9894700.0,1672716.58
44,Guadalajara,2021,Septiembre,10297.1,31925.0,10297100.0,1707219.25
45,Guadalajara,2021,Octubre,11577.8,32995.0,11577800.0,1764438.50
46,Guadalajara,2021,Noviembre,11283.3,31704.7,11283300.0,1695438.50
47,Guadalajara,2021,Diciembre,11859.5,31998.4,11859500.0,1711144.39
48,Guadalajara,2022,Enero,9780.8,31796.1,9780800.0,1700326.20
49,Guadalajara,2022,Febrero,10700.8,31934.3,10700800.0,1707716.58
50,Guadalajara,2022,Marzo,12762.7,33265.2,12762700.0,1778887.70
51,Guadalajara,2022,Abril,10127.1,32331.8,10127100.0,1728973.26
52,Guadalajara,2022,Mayo,11450.4,34181.0,11450400.0,1827860.96
53,Guadalajara,2022,Junio,10555.1,32701.7,10555100.0,1748754.01
54,Guadalajara,2022,Julio,10558.3,32801.0,10558300.0,1754064.17
55,Guadalajara,2022,Agosto,11521.6,33715.9,11521600.0,1802989.30
56,Guadalajara,2022,Septiembre,11772.5,33420.5,11772500.0,1787192.51
57,Guadalajara,2022,Octubre,12574.0,33905.3,12574000.0,1813117.65
58,Guadalajara,2022,Noviembre,12128.5,33139.6,12128500.0,1772171.12
59,Guadalajara,2022,Diciembre,11999.3,32023.6,11999300.0,1712491.98

In [22]:
tren_df['Revenue Tren'] = round( (tren_df['Ingresos por pasaje (Miles de pesos)'] * 1000) / 18.7,2)

In [24]:
tren_df.drop(columns=['Pasajeros transportados (Miles de  pasajeros)'], inplace=True)

In [25]:
tren_df.drop(columns=['Ingresos por pasaje (Miles de pesos)'], inplace=True)

In [27]:
tren_df.drop(columns=['Ciudad'], inplace=True)

In [28]:
tren_df

    Year       Month  Passengers Tren  Revenue Tren
0   2018       Enero        8287800.0    2237759.36
1   2018     Febrero        8033900.0    2128946.52
2   2018       Marzo        8441400.0    2295058.82
3   2018       Abril        8315500.0    2410743.32
4   2018        Mayo        8899000.0    2604812.83
5   2018       Junio        8269900.0    2384465.24
6   2018       Julio        8517500.0    2501213.90
7   2018      Agosto        9023600.0    2639764.71
8   2018  Septiembre        8716600.0    2528855.61
9   2018     Octubre        9590600.0    2721748.66
10  2018   Noviembre        8979200.0    2614320.86
11  2018   Diciembre        8573600.0    2595470.59
12  2019       Enero        8942900.0    2604240.64
13  2019     Febrero        8138600.0    2481748.66
14  2019       Marzo        8813100.0    2601871.66
15  2019       Abril        7859200.0    2516000.00
16  2019        Mayo        8810300.0    2555871.66
17  2019       Junio        8158100.0    2599582.89
18  2019       Julio        8362300.0    2619037.43
19  2019      Agosto        8254400.0    2581288.77
20  2019  Septiembre        7876200.0    2318315.51
21  2019     Octubre        8695000.0    2677625.67
22  2019   Noviembre        8341400.0    2512005.35
23  2019   Diciembre        8181600.0    2455679.14
24  2020       Enero        7813400.0    2420877.01
25  2020     Febrero        7913600.0    2625144.39
26  2020       Marzo        6160500.0    1933812.83
27  2020       Abril        3032000.0     972844.92
28  2020        Mayo        3679700.0    1160978.61
29  2020       Junio        4519700.0    1400406.42
30  2020       Julio        5044300.0    1605951.87
31  2020      Agosto        5278700.0    1674149.73
32  2020  Septiembre        6141600.0    1677705.88
33  2020     Octubre        8569500.0    1680272.73
34  2020   Noviembre        7330400.0    1681903.74
35  2020   Diciembre        8770600.0    1682540.11
36  2021       Enero        7027200.0    1682122.99
37  2021     Febrero        7046400.0    1680866.31
38  2021       Marzo        8583800.0    1705684.49
39  2021       Abril        8260300.0    1689556.15
40  2021        Mayo        9140100.0    1685566.84
41  2021       Junio        9522400.0    1688759.36
42  2021       Julio       10028300.0    1677427.81
43  2021      Agosto        9894700.0    1672716.58
44  2021  Septiembre       10297100.0    1707219.25
45  2021     Octubre       11577800.0    1764438.50
46  2021   Noviembre       11283300.0    1695438.50
47  2021   Diciembre       11859500.0    1711144.39
48  2022       Enero        9780800.0    1700326.20
49  2022     Febrero       10700800.0    1707716.58
50  2022       Marzo       12762700.0    1778887.70
51  2022       Abril       10127100.0    1728973.26
52  2022        Mayo       11450400.0    1827860.96
53  2022       Junio       10555100.0    1748754.01
54  2022       Julio       10558300.0    1754064.17
55  2022      Agosto       11521600.0    1802989.30
56  2022  Septiembre       11772500.0    1787192.51
57  2022     Octubre       12574000.0    1813117.65
58  2022   Noviembre       12128500.0    1772171.12
59  2022   Diciembre       11999300.0    1712491.98